
INPUT:
    # MPR input directory containing mapping file and geophysical attributes
    DIRE: /glade/p/ral/hap/mizukami/pnw-extrems/geospatial_data/geophysical/data_mpr
    # mapping file name
    MAP_FILE: spatialweights_grid_600m_to_HUC12.nc

OUTPUT:
    DIRE: /glade/p/ral/hap/mizukami/pnw-extrems/models/mpr
    PARAM_FILE_NAME: param.nc


# geophysical attribute meta
GEO_ATTR_TYPE:
    climate:
        precipitation: prec
        tempeature: tavg
        wind: wind
        humidity: rh
        aridity: ai
    soil:
        sand: sand_pct
        clay: clay_pct
        silt: silt_pct
        bulk_density: bulk_density
        organic_carbon: soc
    vegetation:
        igpg: vegclass
        canopy_height: ch
        lai: lai
    topography:
        ele: ele_mean
        roughness: ele_std_dev
        slope: slope_mean

# mapping data meta
MAPPING_VARS_META:
    polyid:
        name: hruId
        dim: polyid
        type: int64
    overlaps:
        name: overlaps
        dim: polyid
        type: int32
    intersector:
        name: intersector
        dim: data
        type: int64
    i_index:
        name: i_index
        dim: data
        type: int32
    j_index:
        name: j_index
        dim: data
        type: int32
    weight:
        name: weight
        dim: data
        type: float32
    IDmask:
        name: IDmask
        dim: data
        type: int64
    regridweight:
        name: regridweight
        dim: data
        type: float32
