# transfer function types and parameters
#
# -- convention
# <parameter_name>:
# - coef1
# - coef2
#
# <parameter_name> should match with ['param']['<param_name'>] in param_meta.yml

theta_sat:
 - 1.0
summerLAI:
 - 1.0
heightCanopyTop:
 - 0.75
heightCanopyBottom:
 - 0.5
frozenPrecipMultip:
 - 3
 - 2
